### ISSUE TITLE
Chord VCO potentiometers

### ISSUE THREAD

**Issue by thecluff** [ijnekenamay/HAGIWOs_Module#1]
I'm almost done building the chord VCO! I'm curious which potentiometers you used. Are they B50k?

**Comment by ijnekenamay** [comment]
Thank you for your interest in my project!
I used the B100k as per the original schematic.
It is working fine for me. Please give it a try.
![image](https://user-images.githubusercontent.com/80657332/128287080-64572e04-d290-4818-b2c1-209fec53c49c.png)

**Comment by thecluff** [comment]
Ah right, I should've just double checked that sketch! 🤦🏻‍♂️ Thank you!!

**Comment by daanklijn** [comment]
FYI: 50K pots work as well. The potentiometer acts as a voltage divider here, making it irrelevant which potentiometer value is being used.
