### ISSUE TITLE
Problems 4 ch Sampleplayer

### ISSUE THREAD

**Issue by yentzee** [ijnekenamay/HAGIWOs_Module#5]
Hi,
I did the build but the module doesnt respond at all. When trying to compile your code I get errormessages within the sample data and when uploading the original code nothing happens, also powering using eirorack does not work (I suppose you are pulling off the 5V rail ?
Where are problems regarding the pcb?
I just bought it of ebay and disnt realize it doesnt work. What are the known problems ypu mentioned?
Cheers,
Jens

**Comment by yentzee** [comment]
There doesmt seem any of the pins connecting the 2 pcbs together carrying the gnd. On the pcb with the panel and jacks etc there is no gnd connection to the other pcb :(

**Comment by yentzee** [comment]
So, I just connceted GND from the Eurorack powersupplypins to GND of the 3,5 mm jacks of the top board. Everything is working now using the original script of Hagiwos site. Unfortunately I am completely unexperienced with coding but it seems that the code doesn't compile as there are some mistakes in the part of the sample data. I suppose this is due to how the different samples are seperated of each other. I will try to sort that out and/or read myself into how those tables have to be formated but I guess/hope it wont be too difficult.

**Comment by yentzee** [comment]
ok I saw that there were some , missing between the samples, I added those. now I am getting a scrambled view on the lower 2 rows. also the led for trigger is lighting up but no sound comes out. I can trigger the sound manually though. might have to trace it. It is pretty annoying that the seeeduino ist soldered to the pcb so taking it off to reprogram it is a pain. I highly recommend everybody to use cables ans no wires.

edit: I just traced trig input 1 which seems to lead to r7, after r7 I cant really understand the signalflow as I am a bit in a hurry but it would be great if you could tell me where the problem is as searching for it really is a pain

**Comment by ijnekenamay** [comment]
The sample code is the one I uploaded and should be fine.
When writing to arduino, not only seeduino, it may cause an error if it is connected to TX pin RX pin.
Yhank you.
